# Generated by Django 3.2.7 on 2026-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
